repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml

  - repo: local
    hooks:
      - id: clang-format
        name: clang-format (cpp/cu/hpp)
        entry: clang-format -i
        language: system
        files: \.(cpp|cc|cxx|cu|cuh|h|hpp)$
